# Generated by Django 3.0.2 on 2020-01-25 03:50

import collections
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customcert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcert',
            name='extensions',
            field=jsonfield.fields.JSONField(blank=True, default=list, dump_kwargs={'indent': 4}, help_text='additional x509 certificate extensions', load_kwargs={'object_pairs_hook': collections.OrderedDict}, verbose_name='extensions'),
        ),
        migrations.AlterField(
            model_name='customcert',
            name='serial_number',
            field=models.CharField(blank=True, help_text='leave blank to determine automatically', max_length=48, null=True, verbose_name='serial number'),
        ),
    ]
