# Generated by Django 5.2.7 on 2025-10-06 08:11

import collections
import django_x509.base.models
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0009_alter_ca_digest_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="certificate",
            field=models.TextField(
                blank=True, help_text="Certificate in X.509 PEM format"
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="digest",
            field=models.CharField(
                choices=[
                    ("sha1WithRSAEncryption", "SHA1 with RSA signature"),
                    ("sha224WithRSAEncryption", "SHA224 with RSA signature"),
                    ("sha256WithRSAEncryption", "SHA256 with RSA signature"),
                    ("sha384WithRSAEncryption", "SHA384 with RSA signature"),
                    ("sha512WithRSAEncryption", "SHA512 with RSA signature"),
                    ("ecdsa-with-SHA256", "SHA256 with ECDSA signature"),
                    ("ecdsa-with-SHA384", "SHA384 with ECDSA signature"),
                    ("ecdsa-with-SHA512", "SHA512 with ECDSA signature"),
                    ("dsaWithSHA1", "SHA1 with DSA signature"),
                    ("dsaWithSHA256", "SHA256 with DSA signature"),
                    (
                        "Ed25519",
                        "Edwards-Curve Digital Signature Algorithm with 25519 curve",
                    ),
                    ("Ed448", "Edwards-Curve Digital Signature with 448 curve"),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text="The digest algorithm to use for computing the digest. This is a combination of a hashing algorithm and a signature algorithm. For Edwards-Curves, the hashing algorithm is already baked into the signature.",
                max_length=23,
                verbose_name="digest algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="extensions",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=list,
                dump_kwargs={"indent": 4},
                help_text="Additional x509 certificate extensions",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="key_length",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "---"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                null=True,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="private_key",
            field=models.TextField(
                blank=True, help_text="Private key in X.509 PEM format"
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to determine automatically",
                max_length=48,
                null=True,
                verbose_name="serial number",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="certificate",
            field=models.TextField(
                blank=True, help_text="Certificate in X.509 PEM format"
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="digest",
            field=models.CharField(
                choices=[
                    ("sha1WithRSAEncryption", "SHA1 with RSA signature"),
                    ("sha224WithRSAEncryption", "SHA224 with RSA signature"),
                    ("sha256WithRSAEncryption", "SHA256 with RSA signature"),
                    ("sha384WithRSAEncryption", "SHA384 with RSA signature"),
                    ("sha512WithRSAEncryption", "SHA512 with RSA signature"),
                    ("ecdsa-with-SHA256", "SHA256 with ECDSA signature"),
                    ("ecdsa-with-SHA384", "SHA384 with ECDSA signature"),
                    ("ecdsa-with-SHA512", "SHA512 with ECDSA signature"),
                    ("dsaWithSHA1", "SHA1 with DSA signature"),
                    ("dsaWithSHA256", "SHA256 with DSA signature"),
                    (
                        "Ed25519",
                        "Edwards-Curve Digital Signature Algorithm with 25519 curve",
                    ),
                    ("Ed448", "Edwards-Curve Digital Signature with 448 curve"),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text="The digest algorithm to use for computing the digest. This is a combination of a hashing algorithm and a signature algorithm. For Edwards-Curves, the hashing algorithm is already baked into the signature.",
                max_length=23,
                verbose_name="digest algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="extensions",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=list,
                dump_kwargs={"indent": 4},
                help_text="Additional x509 certificate extensions",
                load_kwargs={"object_pairs_hook": collections.OrderedDict},
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_length",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "---"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                null=True,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="private_key",
            field=models.TextField(
                blank=True, help_text="Private key in X.509 PEM format"
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="serial_number",
            field=models.CharField(
                blank=True,
                help_text="Leave blank to determine automatically",
                max_length=48,
                null=True,
                verbose_name="serial number",
            ),
        ),
    ]
