# Generated by Django 5.2.10 on 2026-01-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0009_alter_ca_digest_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
    ]
