# Generated by Django 5.2.7 on 2025-10-06 08:25

from django.db import migrations


def alter_choices_certificates(apps, schema_editor):
    """Alter old digest choices to new digest choices (also mentioning the encryption algorithm)."""
    Ca = apps.get_model("django_x509", "Ca")
    Ca.objects.filter(digest="sha1").update(digest="sha1WithRSAEncryption")
    Ca.objects.filter(digest="sha224").update(digest="sha224WithRSAEncryption")
    Ca.objects.filter(digest="sha256").update(digest="sha256WithRSAEncryption")
    Ca.objects.filter(digest="sha384").update(digest="sha384WithRSAEncryption")
    Ca.objects.filter(digest="sha512").update(digest="sha512WithRSAEncryption")

    Cert = apps.get_model("django_x509", "Cert")
    Cert.objects.filter(digest="sha1").update(digest="sha1WithRSAEncryption")
    Cert.objects.filter(digest="sha224").update(digest="sha224WithRSAEncryption")
    Cert.objects.filter(digest="sha256").update(digest="sha256WithRSAEncryption")
    Cert.objects.filter(digest="sha384").update(digest="sha384WithRSAEncryption")
    Cert.objects.filter(digest="sha512").update(digest="sha512WithRSAEncryption")


def alter_choices_certificate_reverse(apps, schema_editor):
    """Reverse the operations of alter_choices_certificates."""
    Ca = apps.get_model("django_x509", "Ca")
    Ca.objects.filter(digest="sha1WithRSAEncryption").update(digest="sha1")
    Ca.objects.filter(digest="sha224WithRSAEncryption").update(digest="sha224")
    Ca.objects.filter(digest="sha256WithRSAEncryption").update(digest="sha256")
    Ca.objects.filter(digest="sha384WithRSAEncryption").update(digest="sha384")
    Ca.objects.filter(digest="sha512WithRSAEncryption").update(digest="sha512")

    Cert = apps.get_model("django_x509", "Cert")
    Cert.objects.filter(digest="sha1WithRSAEncryption").update(digest="sha1")
    Cert.objects.filter(digest="sha224WithRSAEncryption").update(digest="sha224")
    Cert.objects.filter(digest="sha256WithRSAEncryption").update(digest="sha256")
    Cert.objects.filter(digest="sha384WithRSAEncryption").update(digest="sha384")
    Cert.objects.filter(digest="sha512WithRSAEncryption").update(digest="sha512")


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0010_alter_ca_certificate_alter_ca_digest_and_more"),
    ]

    operations = [
        migrations.RunPython(
            alter_choices_certificates,
            reverse_code=alter_choices_certificate_reverse
        )
    ]
