# Generated by Django 6.0.1 on 2026-01-17 15:58

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0010_alter_ca_key_length_alter_cert_key_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("256", "256 (ECDSA)"),
                    ("384", "384 (ECDSA)"),
                    ("521", "521 (ECDSA)"),
                    ("1024", "1024 (RSA)"),
                    ("2048", "2048 (RSA)"),
                    ("4096", "4096 (RSA)"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("256", "256 (ECDSA)"),
                    ("384", "384 (ECDSA)"),
                    ("521", "521 (ECDSA)"),
                    ("1024", "1024 (RSA)"),
                    ("2048", "2048 (RSA)"),
                    ("4096", "4096 (RSA)"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
    ]
