# Generated by Django 6.0.3 on 2026-03-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0010_alter_ca_key_length_alter_cert_key_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="ca",
            name="auto_renew",
            field=models.CharField(
                choices=[
                    ("disabled", "disabled"),
                    ("certificates", "auto renew certificates generated by this CA"),
                    ("ca_and_certificates", "auto renew both certificates and CA"),
                ],
                default="disabled",
                max_length=24,
                verbose_name="automatic renewal",
            ),
        ),
        migrations.AddField(
            model_name="ca",
            name="expire_notified",
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="cert",
            name="expire_notified",
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
    ]
