# Generated by Django 5.2.9 on 2026-01-11 11:10

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0010_ca_key_type_cert_key_type_alter_ca_key_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("224", "224"),
                    ("256", "256"),
                    ("384", "384"),
                    ("521", "521"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("224", "224"),
                    ("256", "256"),
                    ("384", "384"),
                    ("521", "521"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
    ]
