# Generated by Django 5.2.7 on 2025-10-06 08:26

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_x509", "0011_auto_20251006_1025"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="digest",
            field=models.CharField(
                choices=[
                    ("sha224WithRSAEncryption", "SHA224 with RSA signature"),
                    ("sha256WithRSAEncryption", "SHA256 with RSA signature"),
                    ("sha384WithRSAEncryption", "SHA384 with RSA signature"),
                    ("sha512WithRSAEncryption", "SHA512 with RSA signature"),
                    ("ecdsa-with-SHA256", "SHA256 with ECDSA signature"),
                    ("ecdsa-with-SHA384", "SHA384 with ECDSA signature"),
                    ("ecdsa-with-SHA512", "SHA512 with ECDSA signature"),
                    ("dsaWithSHA256", "SHA256 with DSA signature"),
                    (
                        "Ed25519",
                        "Edwards-Curve Digital Signature Algorithm with 25519 curve",
                    ),
                    ("Ed448", "Edwards-Curve Digital Signature with 448 curve"),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text="The digest algorithm to use for computing the digest. This is a combination of a hashing algorithm and a signature algorithm. For Edwards-Curves, the hashing algorithm is already baked into the signature.",
                max_length=23,
                verbose_name="digest algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="digest",
            field=models.CharField(
                choices=[
                    ("sha224WithRSAEncryption", "SHA224 with RSA signature"),
                    ("sha256WithRSAEncryption", "SHA256 with RSA signature"),
                    ("sha384WithRSAEncryption", "SHA384 with RSA signature"),
                    ("sha512WithRSAEncryption", "SHA512 with RSA signature"),
                    ("ecdsa-with-SHA256", "SHA256 with ECDSA signature"),
                    ("ecdsa-with-SHA384", "SHA384 with ECDSA signature"),
                    ("ecdsa-with-SHA512", "SHA512 with ECDSA signature"),
                    ("dsaWithSHA256", "SHA256 with DSA signature"),
                    (
                        "Ed25519",
                        "Edwards-Curve Digital Signature Algorithm with 25519 curve",
                    ),
                    ("Ed448", "Edwards-Curve Digital Signature with 448 curve"),
                ],
                default=django_x509.base.models.default_digest_algorithm,
                help_text="The digest algorithm to use for computing the digest. This is a combination of a hashing algorithm and a signature algorithm. For Edwards-Curves, the hashing algorithm is already baked into the signature.",
                max_length=23,
                verbose_name="digest algorithm",
            ),
        ),
    ]
