# Generated by Django 5.2.9 on 2026-01-11 10:55

import django_x509.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_x509", "0002_common_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="ca",
            name="key_type",
            field=models.CharField(
                choices=[("rsa", "RSA"), ("ec", "Elliptic Curve")],
                default="rsa",
                max_length=3,
                verbose_name="key type",
            ),
        ),
        migrations.AddField(
            model_name="cert",
            name="key_type",
            field=models.CharField(
                choices=[("rsa", "RSA"), ("ec", "Elliptic Curve")],
                default="rsa",
                max_length=3,
                verbose_name="key type",
            ),
        ),
        migrations.AddField(
            model_name="customcert",
            name="key_type",
            field=models.CharField(
                choices=[("rsa", "RSA"), ("ec", "Elliptic Curve")],
                default="rsa",
                max_length=3,
                verbose_name="key type",
            ),
        ),
        migrations.AlterField(
            model_name="ca",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("224", "224"),
                    ("256", "256"),
                    ("384", "384"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("224", "224"),
                    ("256", "256"),
                    ("384", "384"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
        migrations.AlterField(
            model_name="customcert",
            name="key_length",
            field=models.CharField(
                choices=[
                    ("224", "224"),
                    ("256", "256"),
                    ("384", "384"),
                    ("512", "512"),
                    ("1024", "1024"),
                    ("2048", "2048"),
                    ("4096", "4096"),
                ],
                default=django_x509.base.models.default_key_length,
                help_text="bits",
                max_length=6,
                verbose_name="key length",
            ),
        ),
    ]
