# Generated by Django 5.2.10 on 2026-01-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_x509", "0002_common_name_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="customcert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
    ]
