# Generated by Django 6.0.5 on 2026-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample_x509", "0003_alter_ca_key_length_alter_cert_key_length_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ca",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="cert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
        migrations.AlterField(
            model_name="customcert",
            name="extensions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="additional x509 certificate extensions",
                verbose_name="extensions",
            ),
        ),
    ]
