# Generated by Django 5.2.13 on 2026-08-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample_x509", "0004_alter_ca_extensions_alter_cert_extensions_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ca",
            options={
                "ordering": ("-created",),
                "verbose_name": "CA",
                "verbose_name_plural": "CAs",
            },
        ),
        migrations.AlterModelOptions(
            name="cert",
            options={
                "ordering": ("-created",),
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
            },
        ),
        migrations.AlterModelOptions(
            name="customcert",
            options={
                "ordering": ("-created",),
                "verbose_name": "certificate",
                "verbose_name_plural": "certificates",
            },
        ),
    ]
